language: bash
sudo: true
before_script:
  - sudo apt-get install unzip
  - wget https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip
  - unzip terraform_0.6.15_linux_amd64.zip -d ./bin
script:
  - ./bin/terraform apply -input=false -var-file vars.tfvars
